export const authTypes = {
  AUTH_LOGIN_LOADING: "AUTH_LOGIN_LOADING",
  AUTH_LOGIN_SUCCESS: "AUTH_LOGIN_SUCCESS",
  AUTH_LOGIN_ERROR: "AUTH_LOGIN_ERROR_",
  AUTH_LOGOUT_SUCCESS: "AUTH_LOGOUT_SUCCESS",
};
