export const productTypes = {
  GET_PRODUCTS_LOADING: "GET_PRODUCTS_LOADING",
  GET_PRODUCTS_SUCCESS: "GET_PRODUCTS_SUCCESS",
  GET_PRODUCTS_ERROR: "GET_PRODUCTS_ERROR",
  ADD_PRODUCT: "ADD_PRODUCT",
  BUY_PRODUCTS_LOADING: "BUY_PRODUCTS_LOADING",
  BUY_PRODUCTS_SUCCESS: "BUY_PRODUCTS_SUCCESS",
  BUY_PRODUCTS_ERROR: "BUY_PRODUCTS_ERROR",
};
